#!/bin/bash                                                                                                                                                                                                 
#SBATCH -t 24:00:00
#SBATCH -n REPLACE_CORES
mpirun -np REPLACE_CORES ./post > post.log

